<?php
    $config=[
        'login_rules'=>[
            [
                'field'=>'user_name',
                'label'=>'User Name',
                'rules'=>'required|valid_email'
            ],
            [
                'field'=>'password',
                'label'=>'Password',
                'rules'=>'required|min_length[8]|max_length[15]'
            ]
        ],
        'create_user'=>[
            [
                'field'=>'email',
                'label'=>'Email',
                'rules'=>'required|valid_email'
            ],
            [
                'field'=>'mobile',
                'label'=>'Mobile',
                'rules'=>'required|is_natural|exact_length[10]'
            ],
            [
                'field'=>'password',
                'label'=>'Password',
                'rules'=>'required|min_length[8]|max_length[15]'
            ]
        ],
        'insert_rules'=>[
            [
                'field'=>'name',
                'label'=>'City Name',
                'rules'=>'required'
            ],
            [
                'field'=>'lat',
                'label'=>'Latitude',
                'rules'=>'required'
            ],
            [
                'field'=>'lng',
                'label'=>'Longitude',
                'rules'=>'required'
            ],
            [
                'field'=>'status',
                'lable'=>'Status',
                'rules'=>'required'
            ]
        ],
        'tours_insert_rules'=>[

            [
                'field'=>'title',
                'label'=>'Title',
                'rules'=>'required'
            ],
            [
                'field'=>'des',
                'label'=>'Description',
                'rules'=>'required'
            ],
            [
                'field'=>'select_category',
                'label'=>'Select Category',
                'rules'=>'required'
            ],
            [
                'field'=>'select_city',
                'label'=>'City',
                'rules'=>'required'
            ],
            [
                'field'=>'price',
                'label'=>'Price',
                'rules'=>'required'
            ],  
        ],
        'slider_insert_rules'=>[
            
            [
                'field'=>'select_city',
                'label'=>'City',
                'rules'=>'required'
            ]
        ],
        'insert_categories'=>[
            [
                'field'=>'category_name',
                'label'=>'Category Name',
                'rules'=>'required'
            ],
        ]
    ];
?>